#!/bin/bash
#PBS -N out_scp_C96  
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev_transfer
#PBS -A NAEFS-DEV
#PBS -l walltime=05:35:00
#PBS -l select=1:ncpus=1:mem=2GB
##PBS -l debug=true

COM_c=/lfs/h2/emc/global/noscrub/walter.kolczynski/global-workflow/COMROOT/fcst_segs_ext 
PDY=20211221
cyc=18

COM_d=/lfs/h2/emc/vpppg/noscrub/bo.cui/BUFR/data_bufr_ctl/C96
mkdir -p $COM_d

dir=gfs.${PDY}/${cyc}/model_data/atmos/history

mkdir -p $COM_d/$dir

rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f00* $COM_d/$dir/
rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f010* $COM_d/$dir/
rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f011* $COM_d/$dir/
rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f012* $COM_d/$dir/
#rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f02* $COM_d/$dir/
#rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f03* $COM_d/$dir/
#rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f04* $COM_d/$dir/
exit

rsync -avzh bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f05* $COM_d/$dir/
exit

exit
rm -rf $COM_d/$dir
mkdir -p $COM_d/$dir
scp  bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*00* $COM_d/$dir/
scp  bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f01* $COM_d/$dir/
scp  bo.cui@cdxfer.wcoss2.ncep.noaa.gov:$COM_c/$dir/*f02* $COM_d/$dir/

